server:
  port: 8079
  servlet:
    context-path: /${spring.application.name}
spring:
  application:
    name: blog-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: blog-post
          uri: lb://blog-post
          predicates:
            - Path=/blog/{segment}/post/**
        - id: blog-blog
          uri: lb://blog-blog
          predicates:
            - Path=/**
      nacos:
        discovery:
          server-addr: 10.82.47.62:8848 # Nacos地址
          sevice: blog-gateway
      service-registry:
        auto-registration:
          enabled: true